### ISSUE TITLE
Error while running the example

### ISSUE THREAD

**Issue by SuPythony** [pngwn/svelte-adapter#15]
Hi,

I copied the code in the example provided in the README and tried to run the app on my local machine. It is successfully compiled but there are errors in the console. Here they are -

```
Uncaught TypeError: Component is not a constructor
    at react.js:12
    at invokePassiveEffectCreate (react-dom.development.js:23487)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at flushPassiveEffectsImpl (react-dom.development.js:23574)
    at unstable_runWithPriority (scheduler.development.js:468)
    at runWithPriority$1 (react-dom.development.js:11276)
    at flushPassiveEffects (react-dom.development.js:23447)
    at react-dom.development.js:23324
    at workLoop (scheduler.development.js:417)
    at flushWork (scheduler.development.js:390)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:157)
```

```
The above error occurred in one of your React components:

    at http://localhost:3000/static/js/vendors~main.chunk.js:36091:73
    at div
    at App (http://localhost:3000/static/js/main.chunk.js:59:83)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```

```
Uncaught TypeError: Component is not a constructor
    at react.js:12
    at invokePassiveEffectCreate (react-dom.development.js:23487)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at flushPassiveEffectsImpl (react-dom.development.js:23574)
    at unstable_runWithPriority (scheduler.development.js:468)
    at runWithPriority$1 (react-dom.development.js:11276)
    at flushPassiveEffects (react-dom.development.js:23447)
    at react-dom.development.js:23324
    at workLoop (scheduler.development.js:417)
    at flushWork (scheduler.development.js:390)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:157)
```

How can I correct this? Please help!

**Comment by pngwn** [comment]
I'll take a look at this, I haven't run the example code in a little while so it is possible that some dependencies may have changed. I am using this successfully in a few projects though, so it _does_ work in general.

**Comment by PaulMaly** [comment]
@pngwn I've got the same error.

**Comment by egleged** [comment]
The same happens when using `toVue` adapter (though not with the example, but with a custom svelte-kit package). Are there some updates on how this could be bypassed?

**Comment by elron** [comment]
I have the same error

**Comment by Krossmaskinen** [comment]
Looks like the example in the codesandbox is using a different version of the app than the code here at github. Different versions of things, different code in the files.
